
# Découverte de numpy

## Installation

In [1]:
%pip install -q numpy


[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


## Les bases

In [2]:
import numpy as np

data = np.zeros((6, 6)) # creates an array of shape (6,6) filled with the value 0
print(data)
print(type(data))
print(data.shape)
print(data.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(6, 6)
float64


In [3]:
data[5][3] = 36
data[4,2] = 42
data[2] = 2

print(data)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 2.  2.  2.  2.  2.  2.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 42.  0.  0.  0.]
 [ 0.  0.  0. 36.  0.  0.]]


In [4]:
data[2] = data[2] * 2
print(data)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 4.  4.  4.  4.  4.  4.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 42.  0.  0.  0.]
 [ 0.  0.  0. 36.  0.  0.]]


In [5]:
print("Third line:")
print(data[2])

print("Five first lines (from 0 (included) to 5 (non inclusive))")
print(data[0:5])

print("Third column")
print(data[:,2])

print("Advanced slice")
print(data[4:6,2:4])

Third line:
[4. 4. 4. 4. 4. 4.]
Five first lines (from 0 (included) to 5 (non inclusive))
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 4.  4.  4.  4.  4.  4.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 42.  0.  0.  0.]]
Third column
[ 0.  0.  4.  0. 42.  0.]
Advanced slice
[[42.  0.]
 [ 0. 36.]]


## Reshape

In [6]:
print(data)
reshaped = data.reshape(3,12)
print(reshaped)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 4.  4.  4.  4.  4.  4.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 42.  0.  0.  0.]
 [ 0.  0.  0. 36.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  4.  4.  4.  4.  4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 42.  0.  0.  0.  0.  0.  0. 36.  0.  0.]]


## Opérations mathématiques

In [7]:
# New array for the following examples

my_array = [
	[1, 2, 3, 4, 500],
	[10, 9, 8, 7, 6],
	[0, 100, 1, 0, -5]
]
array = np.array(my_array)
print(array)


[[  1   2   3   4 500]
 [ 10   9   8   7   6]
 [  0 100   1   0  -5]]


### Arithmétique

In [8]:
array = 2 * array
print(array)

print()

array[1] *= 10
print(array)

[[   2    4    6    8 1000]
 [  20   18   16   14   12]
 [   0  200    2    0  -10]]

[[   2    4    6    8 1000]
 [ 200  180  160  140  120]
 [   0  200    2    0  -10]]


In [9]:
print("Sum of all elements: ", array.sum())

Sum of all elements:  2012


### Analyse

In [10]:
print("Minimum: ", array.min())
print("Maximum: ", array.max())

Minimum:  -10
Maximum:  1000


In [11]:
print("index of the maximum value (in a flatten array)  :", array.argmax())
print("index of the maximum value (by line):            :", array.argmax(0))
print("index of the maximum value (by column)           :", array.argmax(1))


index of the maximum value (in a flatten array)  : 4
index of the maximum value (by line):            : [1 2 1 1 0]
index of the maximum value (by column)           : [4 0 1]


In [12]:
print(array.mean())
print(array.std())

134.13333333333333
245.2682522373321


In [13]:
np.sign(array)

array([[ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 0,  1,  1,  0, -1]])

### Création de tableaux simples

In [14]:
zeroes = np.zeros((3, 5))
print(zeroes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:

ones = np.ones((3, 5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
space = np.linspace(0, 10, 20) # Create an array with 20 points from 0 to 10
print(space)
print(space.shape)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
(20,)


## Les fichiers

### Fichiers csv

In [17]:
%cat dataset.csv

cat: dataset.csv: No such file or directory


In [18]:
dataset = np.loadtxt("dataset/dataset.csv", skiprows=1, delimiter=',')
print(dataset[0:5])
print(dataset.shape)
print(dataset.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3, 3)
float64


In [19]:
np.savetxt("dataset/export.csv", dataset, fmt="%.2f", delimiter=", ")

In [20]:
%cat dataset/export.csv

1.00, 2.00, 3.00
4.00, 5.00, 6.00
7.00, 8.00, 9.00


### Fichiers npy et npz

Formats de fichiers spécifiques à numpy :
- **npy** : Stocker un seul array
- **npz** : Stocker plusieurs arrays

#### Écriture

In [21]:
x = dataset[:,0:2]
y = dataset[:,-1]
print(x)
print(y)

np.save("dataset/x.npy", x)
np.save("dataset/y.npy", y)

np.savez("dataset/dataset.npz", x=x, y=y)

[[1. 2.]
 [4. 5.]
 [7. 8.]]
[3. 6. 9.]


#### Lecture

In [22]:
loaded_x = np.load("dataset/x.npy")

print(loaded_x)

[[1. 2.]
 [4. 5.]
 [7. 8.]]


In [23]:
loaded_dataset = np.load("dataset/dataset.npz")
print(loaded_dataset)

loaded_y = loaded_dataset["y"]
print(loaded_y)

NpzFile 'dataset/dataset.npz' with keys: x, y
[3. 6. 9.]
